version: 2.1

jobs:
  test:
    docker:
      - image: pradapjackie/webdriverio-firefox:latest
    steps:
      - checkout
      # Optionally, install dependencies or run setup commands if needed.
      - run:
          name: Run WebdriverIO Tests
          command: npm run wdio

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
