version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.14-browsers # Use a Node.js image with browsers

    steps:
      - checkout

      - restore_cache: # Cache node_modules
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test # Or your test command (e.g., npx jest)

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test