version: 2.1

executors:
  selenium-executor:
    docker:
      - image: webdriverio/selenium-standalone
    working_directory: ~/project

jobs:
  test:
    executor: selenium-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - run:
          name: Run WebDriverIO Tests
          command: |
            npx wdio run wdio.conf.js

workflows:
  version: 2
  test:
    jobs:
      - test
