version: 2.1

jobs:
  test:
    docker:
      - image: pradapjackie/webdriverio-firefox-amd64:latest
    steps:
      - checkout
      - run:
          name: install dependency
          command: npm i
      - run:
          name: Run WebdriverIO Tests
          command: npm run wdio
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
