version: 2.1

jobs:
  build:
    docker:
      - image: circleci/circleci-cli@0.1.9
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Run WebdriverIO Tests
          command: npx wdio run wdio.conf.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
