version: 2.1

executors:
  webdriverio-executor:
    docker:
      - image: circleci/python:3.8  # You can use any base image that suits your environment
    working_directory: ~/project

jobs:
  setup:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm install --save-dev @wdio/cli
            npx wdio config

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run WebDriverIO Tests
          command: npx wdio run wdio.conf.js

workflows:
  version: 2
  test:
    jobs:
      - setup
      - test:
          requires:
            - setup
