version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.16-browsers # Or cimg/node:lts-browsers (preferred)

    steps:
      - checkout
      - run:
          name: Check Node.js version (CRITICAL!)
          command: node -v  # This will print the Node.js version in the logs
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run wdio